= Defer to Promise
ioisup <ioisup@gmail.com>
:published_at: 2017-03-22
:hp-tags: Typescript, Promise, Defer

ปัญหาของ Promise
ตัว Promise จะต้องรู้สภาพการทำงานของตัวเอง ซึ่งในกรณีที่เรียก request จาก client แล้วรอ response จาก server ทำให้ไม่สามารถที่จะรู้ผลได้ว่าจะเสร็จเมื่อไร ถ้า promise ตั้งแต่แรกอยู่แล้ว อาจจะไม่มีปัญหา แต่ถ้าเป็น event ที่ต้องรอ update ก็จะมีปัญหา

วิธีการแก้ไข น่าจะต้องใช้ await/async

import events = require('events');

class MyEmitter extends events.EventEmitter {}

const myEmitter = new MyEmitter();

let obs=[];

myEmitter.on('event', (id,data) => {
  console.log('an event '+id+' occurred!');
  if(obs[id]){
    obs[id].call(this,data)
    obs[id]=null
  }
});

function delay(id: number) {
    return new Promise<void>(function(resolve,reject) {
        if (id in obs){ 
            reject('dup') 
        }else{
            obs[id]=resolve
        }
    });
}

async function asyncAwait1() {
    console.log("Knock, knock!")
    let res=await delay(1)
    console.log("async/await1! with res="+res)
}

async function asyncAwait2() {
    console.log("Knock, knock!")
    let res=await delay(2)
    console.log("async/await2! with res="+res)
}

asyncAwait1()
asyncAwait2()

myEmitter.emit('event',2,'test21')
myEmitter.emit('event',2,'test22')
myEmitter.emit('event',1,'test1')

